### ISSUE TITLE
Question: Can this run 100% offline?

### ISSUE THREAD

**Issue by greencopper** [mdwiki/mdwiki#76]
Is it possible to use this on a LAN without any Internet connection? Does it require any external CDN's?

**Comment by janbaer** [comment]
Since it’s using a Github repository to store the pages it can’t run without Internet connection.

**Comment by greencopper** [comment]
It doesn't require GitHub to store pages. You can upload it and upload pages and have it serve those just fine. I am talking about the CSS, JS, etc.

**Comment by janbaer** [comment]
I'm sorry, but maybe we're talking about some different things. This web application is using GitHub as backend to store the wiki page for each user separately in his own GitHub repository. With this, the user is not depending on MDWiki in case that the webpage would go down someday, the data would be still stored on GitHub.

**Comment by greencopper** [comment]
I believe we're talking about completely different things. I did a tcpdump to find the answer.
